name: CI/CD

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install package in editable mode
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pytest pytest-cov pytest-asyncio
      - name: Run tests
        run: |
          pytest --cov=src --cov-report=xml tests/
      - name: Upload coverage
        if: matrix.python-version == '3.9'
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          flags: unittests
          fail_ci_if_error: false

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          pip install flake8 black isort mypy
      - name: Run linters
        run: |
          flake8 src tests --max-line-length=100 --extend-ignore=E203,W503
          black --check --line-length=100 src tests
          isort --check --profile=black --line-length=100 src tests

  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          pip install -e .
          pip install mypy types-PyYAML
      - name: Run type checker
        run: |
          mypy src --ignore-missing-imports --no-strict-optional

  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Install pip-audit
        run: |
          pip install pip-audit
      - name: Install dependencies
        run: |
          pip install -e .
      - name: Run security audit
        run: |
          pip-audit
